version: '3.8'

services:
  app:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://admin:password@mongodb:27017/pickone?authSource=admin

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=pickone
    volumes:
      - ./mongodb:/data/db

networks:
  app-network:
    driver: bridge
